FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Mango.Web/Mango.Web.csproj", "Mango.Web/"]
RUN dotnet restore "Mango.Web/Mango.Web.csproj"
COPY . .
WORKDIR "/src/Mango.Web"
RUN dotnet build "Mango.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Mango.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Mango.Web.dll"]
